-- Create posts table (Journal)
CREATE TABLE public.posts (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  excerpt text,
  content text,
  image_url text,
  published_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create cart_items table
CREATE TABLE public.cart_items (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  product_id bigint references public.products(id) not null,
  quantity integer default 1,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  UNIQUE(user_id, product_id)
);

-- Enable RLS
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cart_items ENABLE ROW LEVEL SECURITY;

-- Policies for Posts
CREATE POLICY "Allow public read access to posts" ON public.posts FOR SELECT USING (true);
-- Assumes only authenticated users (admins) can create posts. For now, we'll allow any auth user or you can restrict it.
CREATE POLICY "Allow auth users to create posts" ON public.posts FOR INSERT TO authenticated WITH CHECK (true);

-- Policies for Cart Items
CREATE POLICY "Users can view their own cart items" ON public.cart_items FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users can insert into their own cart" ON public.cart_items FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own cart" ON public.cart_items FOR UPDATE TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own cart" ON public.cart_items FOR DELETE TO authenticated USING (auth.uid() = user_id);
