-- Create categories table
CREATE TABLE public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create products table
CREATE TABLE public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  description text,
  price numeric not null,
  category_id bigint references public.categories(id),
  image_url text,
  is_featured boolean default false,
  is_sale boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- Create policies (modify as needed for your auth setup)
CREATE POLICY "Allow public read access to categories" ON public.categories FOR SELECT USING (true);
CREATE POLICY "Allow public read access to products" ON public.products FOR SELECT USING (true);
